/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gfcl.views;

import gfc.controller.GarmentController;
import gfc.models.Garment;
import gfcl.common_classes.ComboItemsAdder;
import gfcl.common_classes.IdGenerator;
import gfcl.common_classes.PatternChecker;
import gfcl.connector.Connector;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gimhani Uthpala
 */
public class GarmentDetailFrame extends javax.swing.JInternalFrame {

    private GarmentController garmentController;
    private ComboItemsAdder comboItemsAdder;
    /**
     * Creates new form GarmentDetailFrame
     */
    public GarmentDetailFrame() {
        try {
            initComponents();
            
            Connector sConnector=Connector.getSConnector();
            garmentController=sConnector.getGarmentController();
            comboItemsAdder=new ComboItemsAdder();
                    
            garment_id_text.setText(IdGenerator.generateNextGarmentID(garmentController.getLastGarmentId()));
            
            DefaultTableModel dtm=(DefaultTableModel) garment_table.getModel();
            ArrayList<Garment> similarGarmentNames=new ArrayList<>();
            /*
            DefaultTableModel dtm=(DefaultTableModel) garment_table.getModel();
            garment_table.setPreferredScrollableViewportSize(garment_table.getPreferredSize());
            ImageIcon abc=new ImageIcon(getClass().getResource("/gfcl/images/frock-small.jpg"));
            Object data[]={abc,"a","a","s"};
            dtm.addRow(data);*/
            similarGarmentNames = garmentController.getSimilarGarmentNames("");
            for(Garment garment: similarGarmentNames){
                Object rowdata[]={garment.getGarment_id(),garment.getGarment_name(),garment.getIn_stock()};
                dtm.addRow(rowdata);
            }
            garment_edit_combo.setEditable(true);
            comboItemsAdder.addSimilarGarmentNames(garment_edit_combo);
            
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GarmentDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        garment_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        garment_id_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        garment_name_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sewing_stipend_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        waxing_stipend_text = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        cancel_new_button = new javax.swing.JButton();
        save_new_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sewing_stipend_text1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        waxing_stipend_text1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        cancel_edit_button = new javax.swing.JButton();
        save_edit_button = new javax.swing.JButton();
        garment_edit_combo = new javax.swing.JComboBox<>();

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 204));
        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        garment_table.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        garment_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Garment_ID", "Garment_Name", "In_Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        garment_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(garment_table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Garments Available", new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/cloth_types.png")), jPanel1); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel1.setText("Garment ID:");

        garment_id_text.setEditable(false);
        garment_id_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel2.setText("Garment Name:");

        garment_name_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        garment_name_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                garment_name_textKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel3.setText("Sewing stipend:");

        sewing_stipend_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        sewing_stipend_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sewing_stipend_textKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel4.setText("Waxing stipend:");

        waxing_stipend_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        waxing_stipend_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                waxing_stipend_textKeyReleased(evt);
            }
        });

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cancel_new_button.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        cancel_new_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/cancel_icon.png"))); // NOI18N
        cancel_new_button.setText("Cancel");
        cancel_new_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_new_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_new_buttonActionPerformed(evt);
            }
        });

        save_new_button.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        save_new_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/save_small.png"))); // NOI18N
        save_new_button.setText("Save");
        save_new_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_new_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_new_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_new_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel_new_button)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_new_button)
                    .addComponent(save_new_button))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waxing_stipend_text, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(garment_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(garment_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sewing_stipend_text, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 401, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(garment_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(garment_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(sewing_stipend_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(waxing_stipend_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add New Garment Type", new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/shirt_polo.png")), jPanel2); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel5.setText("Garment :");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel7.setText("Sewing stipend:");

        sewing_stipend_text1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        sewing_stipend_text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sewing_stipend_text1KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel8.setText("Waxing stipend:");

        waxing_stipend_text1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        waxing_stipend_text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                waxing_stipend_text1KeyReleased(evt);
            }
        });

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cancel_edit_button.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        cancel_edit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/cancel_icon.png"))); // NOI18N
        cancel_edit_button.setText("Cancel");
        cancel_edit_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_edit_buttonActionPerformed(evt);
            }
        });
        cancel_edit_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cancel_edit_buttonKeyReleased(evt);
            }
        });

        save_edit_button.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        save_edit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/save_small.png"))); // NOI18N
        save_edit_button.setText("Save");
        save_edit_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_edit_buttonActionPerformed(evt);
            }
        });
        save_edit_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                save_edit_buttonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel_edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_edit_button)
                    .addComponent(save_edit_button))
                .addContainerGap())
        );

        garment_edit_combo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        garment_edit_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                garment_edit_comboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(garment_edit_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waxing_stipend_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sewing_stipend_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 467, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(garment_edit_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sewing_stipend_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waxing_stipend_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(66, 66, 66)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edit Garment Stipends", new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/calculator.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_new_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_new_buttonActionPerformed
        try {
            String garment_id=garment_id_text.getText();
            String garment_name=garment_name_text.getText();
            double sewing_stipend=Double.valueOf(sewing_stipend_text.getText());
            double waxing_stipend=Double.valueOf(waxing_stipend_text.getText());
            Garment garment=new Garment(garment_id, garment_name,0, sewing_stipend, waxing_stipend);
            int addNewGarment = garmentController.addNewGarment(garment);
            if(addNewGarment>0){
                JOptionPane.showMessageDialog(this, "New Garment Type Added");
            }else{
                JOptionPane.showMessageDialog(this, "New Garment Type Not Added.Try again");
            }
            createNewForm();
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GarmentDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_new_buttonActionPerformed

    private void save_edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_edit_buttonActionPerformed
        if(garment_edit_combo.getSelectedItem()!=null){
            String selected=garment_edit_combo.getSelectedItem().toString();
            if(selected.length()>4){
                try {
                    String garment_id=selected.substring(selected.length()-4);
                    double sewing_stipend=Double.valueOf(sewing_stipend_text1.getText());
                    double waxing_stipend=Double.valueOf(waxing_stipend_text1.getText());
                    
                    Garment garment=new Garment(garment_id, sewing_stipend, waxing_stipend);
                    int updateGarmentStipends = garmentController.updateGarmentStipends(garment);
                    if(updateGarmentStipends>0){
                        JOptionPane.showMessageDialog(this, "Stipends updated successfully");
                    }else{
                        JOptionPane.showMessageDialog(this, "Stipends update failed");
                    }
                    createNewUpdateForm();
                } catch (RemoteException | SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(GarmentDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }//GEN-LAST:event_save_edit_buttonActionPerformed

    private void cancel_edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_edit_buttonActionPerformed
        try {
            createNewUpdateForm();
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GarmentDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancel_edit_buttonActionPerformed

    private void cancel_new_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_new_buttonActionPerformed
        try {
            createNewForm();
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GarmentDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancel_new_buttonActionPerformed

    private void garment_edit_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_garment_edit_comboItemStateChanged
        if(garment_edit_combo.getSelectedItem()!=null){
            String selected=garment_edit_combo.getSelectedItem().toString();
            if(selected.length()>4){
                try {
                    String garment_id=selected.substring(selected.length()-4);
                    Garment searchGarment = garmentController.searchGarment(garment_id);
                    if(searchGarment!=null){
                        sewing_stipend_text1.setText(String.valueOf(searchGarment.getSewing_stipend()));
                        waxing_stipend_text1.setText(String.valueOf(searchGarment.getWaxing_stipend()));
                    }
                } catch (RemoteException | SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(GarmentDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_garment_edit_comboItemStateChanged

    private void sewing_stipend_text1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sewing_stipend_text1KeyReleased
        String checkDecimal = PatternChecker.checkDecimal(sewing_stipend_text1.getText());
        sewing_stipend_text1.setText(checkDecimal);
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            waxing_stipend_text1.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            garment_edit_combo.requestFocus();
        }
    }//GEN-LAST:event_sewing_stipend_text1KeyReleased

    private void waxing_stipend_text1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_waxing_stipend_text1KeyReleased
        String checkDecimal = PatternChecker.checkDecimal(waxing_stipend_text1.getText());
        waxing_stipend_text1.setText(checkDecimal);
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            save_edit_button.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            sewing_stipend_text1.requestFocus();
        }
    }//GEN-LAST:event_waxing_stipend_text1KeyReleased

    private void save_edit_buttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_save_edit_buttonKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            save_edit_button.doClick();
        }else if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            cancel_edit_button.requestFocus();
        }
    }//GEN-LAST:event_save_edit_buttonKeyReleased

    private void cancel_edit_buttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancel_edit_buttonKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            cancel_edit_button.doClick();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            save_edit_button.requestFocus();
        }
    }//GEN-LAST:event_cancel_edit_buttonKeyReleased

    private void sewing_stipend_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sewing_stipend_textKeyReleased
        String checkDecimal = PatternChecker.checkDecimal(sewing_stipend_text.getText());
        sewing_stipend_text.setText(checkDecimal);
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN ){
            waxing_stipend_text.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            garment_name_text.requestFocus();
        }
    }//GEN-LAST:event_sewing_stipend_textKeyReleased

    private void garment_name_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_garment_name_textKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN ){
            sewing_stipend_text.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            garment_name_text.requestFocus();;
        }
    }//GEN-LAST:event_garment_name_textKeyReleased

    private void waxing_stipend_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_waxing_stipend_textKeyReleased
        String checkDecimal = PatternChecker.checkDecimal(waxing_stipend_text.getText());
        waxing_stipend_text.setText(checkDecimal);
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN ){
            save_new_button.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            sewing_stipend_text.requestFocus();;
        }
    }//GEN-LAST:event_waxing_stipend_textKeyReleased

    private void createNewForm() throws RemoteException, SQLException, ClassNotFoundException{
        garment_id_text.setText(IdGenerator.generateNextGarmentID(garmentController.getLastGarmentId()));
        garment_name_text.setText("");
        sewing_stipend_text.setText("");
        waxing_stipend_text.setText("");
    }
    
    private void createNewUpdateForm() throws RemoteException, SQLException, ClassNotFoundException{
        garment_edit_combo.setSelectedItem(null);
        sewing_stipend_text1.setText("");
        waxing_stipend_text1.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_edit_button;
    private javax.swing.JButton cancel_new_button;
    private javax.swing.JComboBox<String> garment_edit_combo;
    private javax.swing.JTextField garment_id_text;
    private javax.swing.JTextField garment_name_text;
    private javax.swing.JTable garment_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton save_edit_button;
    private javax.swing.JButton save_new_button;
    private javax.swing.JTextField sewing_stipend_text;
    private javax.swing.JTextField sewing_stipend_text1;
    private javax.swing.JTextField waxing_stipend_text;
    private javax.swing.JTextField waxing_stipend_text1;
    // End of variables declaration//GEN-END:variables

    void requestFoucsForm() {
       jTabbedPane1.setSelectedIndex(0);
    }
}
