/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gfcl.views;

import gfc.controller.CustomerOrderController;
import gfc.controller.ExpenseController;
import gfc.controller.IncomeController;
import gfc.controller.StockController;
import gfc.models.Expense;
import gfc.models.Income;
import gfcl.common_classes.ComboItemsAdder;
import gfcl.common_classes.IdGenerator;
import gfcl.common_classes.PatternChecker;
import gfcl.connector.Connector;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gimhani Uthpala
 */
public class IncomeSummaryFrame extends javax.swing.JInternalFrame {

    private ComboItemsAdder cia;
    private ExpenseController expenseController;
    private IncomeController incomeController;
    private StockController stockController;
    private CustomerOrderController customerOrderController;

    /**
     * Creates new form IncomeSummaryFrame
     */
    public IncomeSummaryFrame() {
        try {
            initComponents();

            cia = new ComboItemsAdder();
            Connector connector = Connector.getSConnector();
            expenseController = connector.getExpenseController();
            incomeController = connector.getIncomeController();
            stockController = connector.getStockController();
            customerOrderController = connector.getCustomerOrderController();

            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date();
            date_text.setText(dateFormat.format(date));
            date_text1.setText(dateFormat.format(date));

            expense_type_combo.setEditable(true);
            cia.addSimilarExpensenames(expense_type_combo);

            income_type_combo.setEditable(true);
            cia.addSimilarIncomenames(income_type_combo);

            expense_id_text.setText(IdGenerator.generateNextExpenseID(expenseController.getLastExpId()));
            income_id_text.setText(IdGenerator.generateNextIncomeID(incomeController.getLastIncomeId()));

            Calendar now = Calendar.getInstance();   // Get the current date and time
            int year = now.get(Calendar.YEAR);
            int month = now.get(Calendar.MONTH) + 1;

            monthCombo.setSelectedItem(PatternChecker.getMonthName(month));
            for (int i = 0; i < 50; i++) {
                yearCombo.addItem(String.valueOf(year));
                yearCombo1.addItem(String.valueOf(year));
                year--;
            }

            invalid_date_format_label.setVisible(false);
            invalid_expense_label.setVisible(false);
            no_expense_name_label.setVisible(false);

            invalid_date_format_label1.setVisible(false);
            invalid_income_label.setVisible(false);
            no_income_name_label.setVisible(false);
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(IncomeSummaryFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        monthCombo = new javax.swing.JComboBox<>();
        yearCombo = new javax.swing.JComboBox<>();
        view_monthly_summary = new javax.swing.JButton();
        income_month_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        sales_income_text = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        income_summary_table = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        total_income_text = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        expense_summary_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        total_expense_text = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        buying_material_text = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        profit_text = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        yearCombo1 = new javax.swing.JComboBox<>();
        view_yearly_summary = new javax.swing.JButton();
        income_month_panel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        sales_income_text1 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        income_summary_table1 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        total_income_text1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        expense_summary_table1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        total_expense_text1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        buying_material_text1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        profit_text1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        expense_id_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        expense_type_combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        amount_text = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cancel_button = new javax.swing.JButton();
        save_button = new javax.swing.JButton();
        invalid_date_format_label = new javax.swing.JLabel();
        invalid_expense_label = new javax.swing.JLabel();
        no_expense_name_label = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        date_text1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        income_id_text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        income_type_combo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        amount_text1 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        cancel_button1 = new javax.swing.JButton();
        save_button1 = new javax.swing.JButton();
        invalid_date_format_label1 = new javax.swing.JLabel();
        no_income_name_label = new javax.swing.JLabel();
        invalid_income_label = new javax.swing.JLabel();

        tabpane.setForeground(new java.awt.Color(0, 0, 204));
        tabpane.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N

        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel5.setText("Select month:");

        monthCombo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " " }));

        yearCombo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        yearCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearComboKeyReleased(evt);
            }
        });

        view_monthly_summary.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        view_monthly_summary.setText("View income-expense");
        view_monthly_summary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_monthly_summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_monthly_summaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(view_monthly_summary)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_monthly_summary))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        income_month_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Income Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 2, 11))); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel7.setText("Sales:");

        sales_income_text.setEditable(false);
        sales_income_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        sales_income_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_income_textActionPerformed(evt);
            }
        });

        income_summary_table.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        income_summary_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Income_id", "Income", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        income_summary_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(income_summary_table);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel14.setText("Other income:");

        total_income_text.setEditable(false);
        total_income_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel16.setText("Total income:");

        javax.swing.GroupLayout income_month_panelLayout = new javax.swing.GroupLayout(income_month_panel);
        income_month_panel.setLayout(income_month_panelLayout);
        income_month_panelLayout.setHorizontalGroup(
            income_month_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(income_month_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(income_month_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(income_month_panelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 542, Short.MAX_VALUE)
                        .addComponent(sales_income_text, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addGroup(income_month_panelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, income_month_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_income_text, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        income_month_panelLayout.setVerticalGroup(
            income_month_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(income_month_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(income_month_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sales_income_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(income_month_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(total_income_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Expense Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 2, 11))); // NOI18N

        expense_summary_table.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        expense_summary_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expense_id", "Expense", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        expense_summary_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(expense_summary_table);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel8.setText("Total expense:");

        total_expense_text.setEditable(false);
        total_expense_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel13.setText("Expense to buy materials within month:");

        buying_material_text.setEditable(false);
        buying_material_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel15.setText("Other expenses:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_expense_text, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buying_material_text, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(buying_material_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(total_expense_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel17.setText("Estimated profit:");

        profit_text.setEditable(false);
        profit_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profit_text, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(profit_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(income_month_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(income_month_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel8);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("For month", jPanel6);

        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel18.setText("Select year:");

        yearCombo1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        yearCombo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearCombo1KeyReleased(evt);
            }
        });

        view_yearly_summary.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        view_yearly_summary.setText("View income-expense");
        view_yearly_summary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_yearly_summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_yearly_summaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yearCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(view_yearly_summary)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(yearCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_yearly_summary))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        income_month_panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Income Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 2, 11))); // NOI18N

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel19.setText("Sales:");

        sales_income_text1.setEditable(false);
        sales_income_text1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        income_summary_table1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        income_summary_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Income_id", "Income", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        income_summary_table1.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(income_summary_table1);

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel20.setText("Other income:");

        total_income_text1.setEditable(false);
        total_income_text1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel21.setText("Total income:");

        javax.swing.GroupLayout income_month_panel1Layout = new javax.swing.GroupLayout(income_month_panel1);
        income_month_panel1.setLayout(income_month_panel1Layout);
        income_month_panel1Layout.setHorizontalGroup(
            income_month_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(income_month_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(income_month_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(income_month_panel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                        .addComponent(sales_income_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addGroup(income_month_panel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, income_month_panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_income_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        income_month_panel1Layout.setVerticalGroup(
            income_month_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(income_month_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(income_month_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(sales_income_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(income_month_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(total_income_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Expense Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 2, 11))); // NOI18N

        expense_summary_table1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        expense_summary_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expense_id", "Expense", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        expense_summary_table1.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(expense_summary_table1);

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel22.setText("Total expense:");

        total_expense_text1.setEditable(false);
        total_expense_text1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel23.setText("Expense to buy materials within month:");

        buying_material_text1.setEditable(false);
        buying_material_text1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel24.setText("Other expenses:");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_expense_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buying_material_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(buying_material_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(total_expense_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel25.setText("Estimated profit:");

        profit_text1.setEditable(false);
        profit_text1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profit_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(profit_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(income_month_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(income_month_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel9);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("For year", jPanel7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabpane.addTab("View Expense-Income summary", new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/report16.png")), jPanel2); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel1.setText("Date of Expense:");

        date_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        date_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                date_textKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                date_textKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel2.setText("Expense Id:");

        expense_id_text.setEditable(false);
        expense_id_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel3.setText("Add Expense Type:");

        expense_type_combo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        expense_type_combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                expense_type_comboKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel4.setText("Expense Amount: Rs.");

        amount_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        amount_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amount_textKeyReleased(evt);
            }
        });

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cancel_button.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/cancel_icon.png"))); // NOI18N
        cancel_button.setText("Cancel");
        cancel_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        save_button.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/save_small.png"))); // NOI18N
        save_button.setText("Save");
        save_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel_button)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_button)
                    .addComponent(save_button))
                .addContainerGap())
        );

        invalid_date_format_label.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        invalid_date_format_label.setForeground(new java.awt.Color(255, 0, 0));
        invalid_date_format_label.setText("invalid date format!");

        invalid_expense_label.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        invalid_expense_label.setForeground(new java.awt.Color(255, 0, 0));
        invalid_expense_label.setText("invalid  expense value!");

        no_expense_name_label.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        no_expense_name_label.setForeground(new java.awt.Color(255, 0, 0));
        no_expense_name_label.setText("Please give an expense name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(amount_text, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invalid_expense_label, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addGap(410, 410, 410))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(invalid_date_format_label, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(expense_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(expense_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(no_expense_name_label)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(date_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(expense_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invalid_date_format_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(expense_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_expense_name_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amount_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invalid_expense_label))
                .addGap(60, 60, 60)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(506, Short.MAX_VALUE))
        );

        tabpane.addTab("Add Expense", new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/report--minus.png")), jPanel1); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel9.setText("Date of Expense:");

        date_text1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        date_text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_text1ActionPerformed(evt);
            }
        });
        date_text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                date_text1KeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel10.setText("Income Id:");

        income_id_text.setEditable(false);
        income_id_text.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel11.setText("Add Income Type:");

        income_type_combo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        income_type_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                income_type_comboItemStateChanged(evt);
            }
        });
        income_type_combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                income_type_comboKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel12.setText("Income Amount: Rs.");

        amount_text1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        amount_text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amount_text1KeyReleased(evt);
            }
        });

        jPanel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cancel_button1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        cancel_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/cancel_icon.png"))); // NOI18N
        cancel_button1.setText("Cancel");
        cancel_button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_button1ActionPerformed(evt);
            }
        });

        save_button1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        save_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/save_small.png"))); // NOI18N
        save_button1.setText("Save");
        save_button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel_button1)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_button1)
                    .addComponent(save_button1))
                .addContainerGap())
        );

        invalid_date_format_label1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        invalid_date_format_label1.setForeground(new java.awt.Color(255, 0, 0));
        invalid_date_format_label1.setText("invalid date format!");

        no_income_name_label.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        no_income_name_label.setForeground(new java.awt.Color(255, 0, 0));
        no_income_name_label.setText("Please give an income name");

        invalid_income_label.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        invalid_income_label.setForeground(new java.awt.Color(255, 0, 0));
        invalid_income_label.setText("invalid  income value!");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addComponent(date_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(invalid_date_format_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(income_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(income_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(no_income_name_label)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(amount_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(invalid_income_label, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(date_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(income_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invalid_date_format_label1))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(income_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_income_name_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(amount_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invalid_income_label))
                .addGap(60, 60, 60)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(795, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel14);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );

        tabpane.addTab("Add Income", new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/report--plus.png")), jPanel13); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        if (expense_type_combo.getSelectedItem() == null || !PatternChecker.checkDecimaldirect(amount_text.getText()) || !PatternChecker.dateFormatChecker(date_text.getText())) {
            if (expense_type_combo.getSelectedItem() == null) {
                no_expense_name_label.setVisible(true);
            }
            if (!PatternChecker.checkDecimaldirect(amount_text.getText())) {
                invalid_expense_label.setVisible(true);
            }
            if (!PatternChecker.dateFormatChecker(date_text.getText())) {
                invalid_date_format_label.setVisible(true);
            }
        } else {
            try {
                String expense_id = expense_id_text.getText();
                String expense_name = expense_type_combo.getSelectedItem().toString();
                double amount = Double.valueOf(amount_text.getText());
                double amount_r = PatternChecker.round(amount, 2);
                if (amount != amount_r) {
                    amount = amount_r;
                    amount_text.setText(String.valueOf(amount));
                }
                
                String date = date_text.getText();
                Expense expense = new Expense(expense_id, expense_name, date, amount);
                System.out.println(expense_name);
                int addNewExpense = 0;
                addNewExpense = expenseController.addNewExpense(expense);
                if (addNewExpense > 0) {
                    JOptionPane.showMessageDialog(this, "Expense added successfully");
                    createNewForm("Expense");
                } else {
                    JOptionPane.showMessageDialog(this, "Expense failed to add!");
                }

            } catch (RemoteException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(IncomeSummaryFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        try {
            createNewForm("Expense");
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(IncomeSummaryFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void view_monthly_summaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_monthly_summaryActionPerformed
        try {
            int month = PatternChecker.getMonthNumber(monthCombo.getSelectedItem().toString());
            int year = Integer.valueOf(yearCombo.getSelectedItem().toString());
            ArrayList<Expense> monthlyExpenses = new ArrayList<>();
            monthlyExpenses = expenseController.getMonthlyExpenses(year, month);
            DefaultTableModel dtm = (DefaultTableModel) expense_summary_table.getModel();
            double expense_sum = 0;
            for (Expense expense : monthlyExpenses) {
                Object rowdata[] = {expense.getExpense_id(), expense.getExpense(), expense.getDateOfExp(), expense.getAmount()};
                dtm.addRow(rowdata);
                expense_sum += expense.getAmount();
            }
            buying_material_text.setText(String.valueOf(PatternChecker.round(stockController.getMonthlyCostForMaterial(year, month), 2)));
            total_expense_text.setText(String.valueOf(PatternChecker.round((expense_sum + Double.valueOf(sales_income_text.getText())), 2)));

            ArrayList<Income> monthlyIncomes = new ArrayList<>();
            monthlyIncomes = incomeController.getMonthlyIncomeList(year, month);
            DefaultTableModel dtm_in = (DefaultTableModel) income_summary_table.getModel();
            double income_sum = 0;
            for (Income income : monthlyIncomes) {
                Object rowdata[] = {income.getIncome_id(), income.getIncome(), income.getDateOfInc(), income.getAmount()};
                dtm_in.addRow(rowdata);
                income_sum += income.getAmount();
            }
            sales_income_text.setText(String.valueOf(PatternChecker.round(customerOrderController.getMonthlySalesIncome(year, month), 2)));
            total_income_text.setText(String.valueOf(PatternChecker.round(income_sum + Double.valueOf(sales_income_text1.getText()), 2)));

            profit_text.setText(String.valueOf(Double.valueOf(total_income_text.getText()) - Double.valueOf(total_expense_text.getText())));
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(IncomeSummaryFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_view_monthly_summaryActionPerformed

    private void cancel_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_button1ActionPerformed
        try {
            createNewForm("Income");
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(IncomeSummaryFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancel_button1ActionPerformed

    private void save_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_button1ActionPerformed
        if (income_type_combo.getSelectedItem() == null || !PatternChecker.checkDecimaldirect(amount_text1.getText()) || !PatternChecker.dateFormatChecker(date_text1.getText())) {
            if (income_type_combo.getSelectedItem() == null) {
                no_income_name_label.setVisible(true);
            }
            if (!PatternChecker.checkDecimaldirect(amount_text1.getText())) {
                invalid_income_label.setVisible(true);
            }
            if (!PatternChecker.dateFormatChecker(date_text1.getText())) {
                invalid_date_format_label1.setVisible(true);
            }
        } else {
            try {
                String income_id = income_id_text.getText();
                String income_name = income_type_combo.getSelectedItem().toString();
                double amount = Double.valueOf(amount_text1.getText());
                double amount_r = PatternChecker.round(amount, 2);
                if (amount != amount_r) {
                    amount = amount_r;
                    amount_text1.setText(String.valueOf(amount));
                }
                String date = date_text1.getText();
                Income income = new Income(income_id, income_id, date, amount);

                int addNewIncome = 0;
                addNewIncome = incomeController.addNewIncome(income);
                if (addNewIncome > 0) {
                    JOptionPane.showMessageDialog(this, "Income added successfully");
                    createNewForm("Income");
                } else {
                    JOptionPane.showMessageDialog(this, "Income failed to add!");
                }

            } catch (RemoteException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(IncomeSummaryFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_save_button1ActionPerformed

    private void view_yearly_summaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_yearly_summaryActionPerformed
        try {

            int year = Integer.valueOf(yearCombo1.getSelectedItem().toString());
            ArrayList<Expense> yearlyExpenses = new ArrayList<>();
            yearlyExpenses = expenseController.getYearlyExpenses(year);
            DefaultTableModel dtm = (DefaultTableModel) expense_summary_table1.getModel();
            double expense_sum = 0;
            for (Expense expense : yearlyExpenses) {
                Object rowdata[] = {expense.getExpense_id(), expense.getExpense(), expense.getDateOfExp(), expense.getAmount()};
                dtm.addRow(rowdata);
                expense_sum += expense.getAmount();
            }
            buying_material_text1.setText(String.valueOf(PatternChecker.round(stockController.getYearlyCostForMaterial(year), 2)));
            total_expense_text1.setText(String.valueOf(PatternChecker.round((expense_sum + Double.valueOf(buying_material_text1.getText())), 2)));

            ArrayList<Income> yearlyIncomes = new ArrayList<>();
            yearlyIncomes = incomeController.getYearlyIncomeList(year);
            DefaultTableModel dtm_in = (DefaultTableModel) income_summary_table1.getModel();
            double income_sum = 0;
            for (Income income : yearlyIncomes) {
                Object rowdata[] = {income.getIncome_id(), income.getIncome(), income.getDateOfInc(), income.getAmount()};
                dtm_in.addRow(rowdata);
                income_sum += income.getAmount();
            }
            sales_income_text1.setText(String.valueOf(PatternChecker.round(customerOrderController.getYearlySalesIncome(year), 2)));
            total_income_text1.setText(String.valueOf(PatternChecker.round((income_sum + Double.valueOf(sales_income_text1.getText())), 2)));

            profit_text1.setText(String.valueOf(Double.valueOf(total_income_text1.getText()) - Double.valueOf(total_expense_text1.getText())));
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(IncomeSummaryFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_view_yearly_summaryActionPerformed

    private void date_text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_text1ActionPerformed

    private void yearCombo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearCombo1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            view_yearly_summary.doClick();
        }
    }//GEN-LAST:event_yearCombo1KeyReleased

    private void yearComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearComboKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            view_monthly_summary.doClick();
        }
    }//GEN-LAST:event_yearComboKeyReleased

    private void date_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date_textKeyPressed

    }//GEN-LAST:event_date_textKeyPressed

    private void expense_type_comboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expense_type_comboKeyReleased
        no_expense_name_label.setVisible(false);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (expense_type_combo.getSelectedItem() != null) {
                if (expense_type_combo.getSelectedItem().toString().trim().length() == 0) {
                    //if an empty string present
                    no_expense_name_label.setVisible(true);
                }
            } else {
                //if selected item is null
                no_expense_name_label.setVisible(true);
            }
        }
    }//GEN-LAST:event_expense_type_comboKeyReleased

    private void date_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date_textKeyReleased
        invalid_date_format_label.setVisible(false);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boolean dateFormatChecker = PatternChecker.dateFormatChecker(date_text.getText());
            if (!dateFormatChecker) {
                invalid_date_format_label.setVisible(true);
            }
        }
    }//GEN-LAST:event_date_textKeyReleased

    private void date_text1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date_text1KeyReleased
        invalid_date_format_label.setVisible(false);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boolean dateFormatChecker = PatternChecker.dateFormatChecker(date_text1.getText());
            if (!dateFormatChecker) {
                invalid_date_format_label1.setVisible(true);
            }
        }
    }//GEN-LAST:event_date_text1KeyReleased

    private void income_type_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_income_type_comboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_income_type_comboItemStateChanged

    private void income_type_comboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_income_type_comboKeyReleased
        no_income_name_label.setVisible(false);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (income_type_combo.getSelectedItem() != null) {
                if (income_type_combo.getSelectedItem().toString().trim().length() == 0) {
                    //if an empty string present
                    no_income_name_label.setVisible(true);
                }
            } else {
                //if selected item is null
                no_income_name_label.setVisible(true);
            }
        }
    }//GEN-LAST:event_income_type_comboKeyReleased

    private void amount_text1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amount_text1KeyReleased
        invalid_income_label.setVisible(false);
        String checkDecimal = PatternChecker.checkDecimal(amount_text1.getText());
        amount_text1.setText(checkDecimal);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            invalid_income_label.setVisible(true);
        }
    }//GEN-LAST:event_amount_text1KeyReleased

    private void amount_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amount_textKeyReleased
        invalid_expense_label.setVisible(false);
        String checkDecimal = PatternChecker.checkDecimal(amount_text.getText());
        amount_text.setText(checkDecimal);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            invalid_expense_label.setVisible(true);
        }
    }//GEN-LAST:event_amount_textKeyReleased

    private void sales_income_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_income_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sales_income_textActionPerformed

    void createNewForm(String type) throws RemoteException, SQLException, ClassNotFoundException {
        if (type == "Expense") {
            expense_id_text.setText(IdGenerator.generateNextExpenseID(expenseController.getLastExpId()));
            amount_text.setText("");
            expense_type_combo.setSelectedItem(null);
            invalid_date_format_label.setVisible(false);
            invalid_expense_label.setVisible(false);
            no_expense_name_label.setVisible(false);
        } else {
            income_id_text.setText(IdGenerator.generateNextExpenseID(incomeController.getLastIncomeId()));
            amount_text1.setText("");
            income_type_combo.setSelectedItem(null);
            invalid_date_format_label1.setVisible(false);
            invalid_income_label.setVisible(false);
            no_income_name_label.setVisible(false);

        }
    }

    void focustabbedpane(int num) {
        tabpane.setSelectedIndex(num);
    }

    void requestFoucsForm() {
        switch (tabpane.getSelectedIndex()) {
            case 0:
                monthCombo.requestFocus();
                break;
            case 1:
                expense_type_combo.requestFocus();
                break;
            default:
                income_type_combo.requestFocus();
                break;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_text;
    private javax.swing.JTextField amount_text1;
    private javax.swing.JTextField buying_material_text;
    private javax.swing.JTextField buying_material_text1;
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton cancel_button1;
    private javax.swing.JTextField date_text;
    private javax.swing.JTextField date_text1;
    private javax.swing.JTextField expense_id_text;
    private javax.swing.JTable expense_summary_table;
    private javax.swing.JTable expense_summary_table1;
    private javax.swing.JComboBox<String> expense_type_combo;
    private javax.swing.JTextField income_id_text;
    private javax.swing.JPanel income_month_panel;
    private javax.swing.JPanel income_month_panel1;
    private javax.swing.JTable income_summary_table;
    private javax.swing.JTable income_summary_table1;
    private javax.swing.JComboBox<String> income_type_combo;
    private javax.swing.JLabel invalid_date_format_label;
    private javax.swing.JLabel invalid_date_format_label1;
    private javax.swing.JLabel invalid_expense_label;
    private javax.swing.JLabel invalid_income_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JLabel no_expense_name_label;
    private javax.swing.JLabel no_income_name_label;
    private javax.swing.JTextField profit_text;
    private javax.swing.JTextField profit_text1;
    private javax.swing.JTextField sales_income_text;
    private javax.swing.JTextField sales_income_text1;
    private javax.swing.JButton save_button;
    private javax.swing.JButton save_button1;
    private javax.swing.JTabbedPane tabpane;
    private javax.swing.JTextField total_expense_text;
    private javax.swing.JTextField total_expense_text1;
    private javax.swing.JTextField total_income_text;
    private javax.swing.JTextField total_income_text1;
    private javax.swing.JButton view_monthly_summary;
    private javax.swing.JButton view_yearly_summary;
    private javax.swing.JComboBox<String> yearCombo;
    private javax.swing.JComboBox<String> yearCombo1;
    // End of variables declaration//GEN-END:variables
}
