/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gfcl.views;

import gfc.controller.DailyCoverageController;
import gfc.controller.GarmentController;
import gfc.models.DailyCoverage;
import gfc.models.Garment;
import gfcl.common_classes.GUIitemsValidator;
import gfcl.connector.Connector;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Gimhani Uthpala
 */
public class ProductionDetailFrame extends javax.swing.JInternalFrame {

    private GarmentController garmentController;
    private DailyCoverageController dailyCoverageController;

    /**
     * Creates new form ProductionDetailFrame
     */
    public ProductionDetailFrame() {
        try {
            initComponents();

            Connector sConnector = Connector.getSConnector();
            garmentController = sConnector.getGarmentController();
            dailyCoverageController = sConnector.getDailyCoverageController();

            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date();
            date_text.setText(dateFormat.format(date));

            add_to_table_button.setEnabled(false);

            this.garment_combo.setEditable(true);
            JTextComponent garmentCombo = (JTextComponent) garment_combo.getEditor().getEditorComponent();
            garmentCombo.addKeyListener(new KeyAdapter() {

                @Override
                public void keyReleased(KeyEvent e) {
                    try {
                        String item = (String) garment_combo.getEditor().getItem();
                        ArrayList<Object> list = new ArrayList();

                        ArrayList<Garment> similar = garmentController.getSimilarGarmentNames(item);
                        for (int i = 0; i < similar.size(); i++) {
                            list.add(similar.get(i).getGarment_name() + " " + similar.get(i).getGarment_id());
                        }
                        GUIitemsValidator.addItemToCombo(list, garment_combo);
                    } catch (ClassNotFoundException | SQLException | RemoteException ex) {
                        Logger.getLogger(GUIitemsValidator.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            });

            this.garment_inpro_combo.setEditable(true);
            JTextComponent garmentInCombo = (JTextComponent) garment_inpro_combo.getEditor().getEditorComponent();
            garmentInCombo.addKeyListener(new KeyAdapter() {

                @Override
                public void keyReleased(KeyEvent e) {
                    try {
                        String item = (String) garment_inpro_combo.getEditor().getItem();
                        ArrayList<Object> list = new ArrayList();

                        ArrayList<Garment> similar = garmentController.getSimilarGarmentNames(item);
                        for (int i = 0; i < similar.size(); i++) {
                            list.add(similar.get(i).getGarment_name() + " " + similar.get(i).getGarment_id());
                        }
                        GUIitemsValidator.addItemToCombo(list, garment_inpro_combo);
                    } catch (ClassNotFoundException | SQLException | RemoteException ex) {
                        Logger.getLogger(GUIitemsValidator.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            });
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ProductionDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_pane_out = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date_text = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        tabpane_in = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        garment_combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cutting_spinner = new javax.swing.JSpinner();
        sewing_spinner = new javax.swing.JSpinner();
        dyeing_spinner = new javax.swing.JSpinner();
        washing_spinner = new javax.swing.JSpinner();
        completing_spinner = new javax.swing.JSpinner();
        sewing_finish_spinner = new javax.swing.JSpinner();
        jPanel11 = new javax.swing.JPanel();
        save_by_garment_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        processes_combo = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        garment_inpro_combo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        no_of_garments_spinner = new javax.swing.JSpinner();
        add_to_table_button = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        process_table = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        cancel_button2 = new javax.swing.JButton();
        save_by_process_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Date:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(date_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Select garment:");

        garment_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                garment_comboItemStateChanged(evt);
            }
        });

        jLabel3.setText("Cuttings:");

        jLabel5.setText("Sewings:");

        jLabel6.setText("Dyeings:");

        jLabel8.setText("Washings:");

        jLabel9.setText("Fininsh sewings:");

        jLabel11.setText("Completions:");

        cutting_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cutting_spinnerStateChanged(evt);
            }
        });

        sewing_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sewing_spinnerStateChanged(evt);
            }
        });

        dyeing_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dyeing_spinnerStateChanged(evt);
            }
        });

        washing_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                washing_spinnerStateChanged(evt);
            }
        });

        completing_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                completing_spinnerStateChanged(evt);
            }
        });

        sewing_finish_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sewing_finish_spinnerStateChanged(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        save_by_garment_button.setText("Save");
        save_by_garment_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_by_garment_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addComponent(save_by_garment_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel_button)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_button)
                    .addComponent(save_by_garment_button))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(garment_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(washing_spinner, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(dyeing_spinner)
                                        .addComponent(sewing_spinner)
                                        .addComponent(cutting_spinner)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel11))
                                    .addGap(49, 49, 49)
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sewing_finish_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(completing_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(garment_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cutting_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sewing_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dyeing_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(washing_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sewing_finish_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(completing_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel10);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        tabpane_in.addTab("By Garment", jPanel8);

        jLabel4.setText("Select process:");

        processes_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cutting", "Sewing", "Dyeing", "Washing and Drying", "Finish sewing", "Finishing" }));

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Select Garment:");

        garment_inpro_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                garment_inpro_comboItemStateChanged(evt);
            }
        });

        jLabel10.setText("No.Of Garments:");

        no_of_garments_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                no_of_garments_spinnerStateChanged(evt);
            }
        });

        add_to_table_button.setText("Add");
        add_to_table_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_table_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_to_table_button)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(garment_inpro_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(no_of_garments_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(garment_inpro_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(no_of_garments_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_to_table_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        process_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Process", "GarmentID", "Garment", "No. of Garments"
            }
        ));
        jScrollPane4.setViewportView(process_table);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cancel_button2.setText("Cancel");
        cancel_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_button2ActionPerformed(evt);
            }
        });

        save_by_process_button.setText("Save");
        save_by_process_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_by_process_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_by_process_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel_button2)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_button2)
                    .addComponent(save_by_process_button))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(processes_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(processes_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel9);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        tabpane_in.addTab("By Process", jPanel7);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabpane_in)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(tabpane_in)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        tab_pane_out.addTab("Add Daily Coverage", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );

        tab_pane_out.addTab("Add cloth cuttings", jPanel2);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );

        tab_pane_out.addTab("View Production", jPanel15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_pane_out)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_pane_out)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_by_garment_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_by_garment_buttonActionPerformed
        try {
            String date = date_text.getText();
            String garment = garment_combo.getSelectedItem().toString();
            String garment_id = garment.substring(garment.length() - 4, garment.length());
            int no_of_cut = Integer.valueOf(cutting_spinner.getValue().toString());
            int no_of_sewn = Integer.valueOf(sewing_spinner.getValue().toString());
            int no_of_dyed = Integer.valueOf(dyeing_spinner.getValue().toString());
            int no_of_washdry = Integer.valueOf(washing_spinner.getValue().toString());
            int no_of_sewfinish = Integer.valueOf(sewing_finish_spinner.getValue().toString());
            int no_of_finish = Integer.valueOf(completing_spinner.getValue().toString());
            DailyCoverage dc = new DailyCoverage(garment_id, date, no_of_cut, no_of_sewn, no_of_dyed, no_of_washdry, no_of_sewfinish, no_of_finish);
            int addDailyCoverage = 0;
            if (dailyCoverageController.searchDailyCoverage(date, garment_id) != null) {
                addDailyCoverage = dailyCoverageController.updateDailyCoverage(dc);
            } else {
                addDailyCoverage = dailyCoverageController.addDailyCoverage(dc);
            }
            if (addDailyCoverage > 0) {
                JOptionPane.showMessageDialog(this, "Daily coverage added!");
            } else {
                JOptionPane.showMessageDialog(this, "Daily coverage update was failed!");
            }
            garment_combo.setSelectedItem("");
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ProductionDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_by_garment_buttonActionPerformed

    private void garment_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_garment_comboItemStateChanged
        try {
            String date = date_text.getText();
            String garment = garment_combo.getSelectedItem().toString();
            String garment_id = "";
            if (garment.length() > 5) {
                garment_id = garment.substring(garment.length() - 4, garment.length());
            }
            DailyCoverage searchDailyCoverage = dailyCoverageController.searchDailyCoverage(date, garment_id);
            if (searchDailyCoverage != null) {
                cutting_spinner.setValue(searchDailyCoverage.getNo_of_cut());
                sewing_spinner.setValue(searchDailyCoverage.getNo_of_sewn());
                dyeing_spinner.setValue(searchDailyCoverage.getNo_of_dyed());
                washing_spinner.setValue(searchDailyCoverage.getNo_of_washdry());
                sewing_finish_spinner.setValue(searchDailyCoverage.getNo_of_sewfinish());
                completing_spinner.setValue(searchDailyCoverage.getNo_of_finish());
            } else {
                cutting_spinner.setValue(0);
                sewing_spinner.setValue(0);
                dyeing_spinner.setValue(0);
                washing_spinner.setValue(0);
                sewing_finish_spinner.setValue(0);
                completing_spinner.setValue(0);
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ProductionDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_garment_comboItemStateChanged

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        garment_combo.setSelectedItem(null);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void cancel_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel_button2ActionPerformed

    private void save_by_process_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_by_process_buttonActionPerformed

        String date = date_text.getText();
        DefaultTableModel dtm = (DefaultTableModel) process_table.getModel();
        int res=1;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            String garment_id = dtm.getValueAt(i, 1).toString();

            try {
                String process = dtm.getValueAt(i, 0).toString();
                int no_of_cut;
                int no_of_sewn;
                int no_of_dyed;
                int no_of_wash_dry;
                int no_of_sewfinish;
                int no_of_finish;
                DailyCoverage dc;
                switch (process) {
                    case "Cutting":
                        no_of_cut = Integer.valueOf(dtm.getValueAt(i, 3).toString());
                        dc = new DailyCoverage(garment_id, date, no_of_cut);
                        res=dailyCoverageController.updateDailyCoverageCut(dc);
                        break;
                    case "Sewing":
                        no_of_sewn = Integer.valueOf(dtm.getValueAt(i, 3).toString());
                        dc = new DailyCoverage(garment_id, date, no_of_sewn);
                        res=dailyCoverageController.updateDailyCoverageSewn(dc);
                        break;
                    case "Dyeing":
                        no_of_dyed = Integer.valueOf(dtm.getValueAt(i, 3).toString());
                        dc = new DailyCoverage(garment_id, date, no_of_dyed);
                        res=dailyCoverageController.updateDailyCoverageDyed(dc);
                        break;
                    case "Washing and Drying":
                        no_of_wash_dry = Integer.valueOf(dtm.getValueAt(i, 3).toString());
                        dc = new DailyCoverage(garment_id, date, no_of_wash_dry);
                        res=dailyCoverageController.updateDailyCoverageWashDry(dc);
                        break;
                    case "Finish sewing":
                        no_of_sewfinish = Integer.valueOf(dtm.getValueAt(i, 3).toString());
                        dc = new DailyCoverage(garment_id, date, no_of_sewfinish);
                        res=dailyCoverageController.updateDailyCoverageSewfinish(dc);
                        break;
                    case "Finishing":
                        no_of_finish = Integer.valueOf(dtm.getValueAt(i, 3).toString());
                        dc = new DailyCoverage(garment_id, date, no_of_finish);
                        res=dailyCoverageController.updateDailyCoverageFinish(dc);
                        break;
                }
                if(res<=0){
                    JOptionPane.showMessageDialog(this, "Daily Coverages failed!");
                    break;
                }
            } catch (RemoteException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ProductionDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(res>0){
            JOptionPane.showMessageDialog(this, "Daily Coverages successfully added!");
        }
        process_table.removeAll();
        
    }//GEN-LAST:event_save_by_process_buttonActionPerformed

    private void add_to_table_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_table_buttonActionPerformed
        String process = processes_combo.getSelectedItem().toString();
        String garment = garment_inpro_combo.getSelectedItem().toString();
        String garment_id = garment.substring(garment.length() - 4, garment.length());
        String garment_name = garment.substring(0, garment.length() - 4);
        int no_of_garments = Integer.valueOf(no_of_garments_spinner.getValue().toString());

        DefaultTableModel tableModel = (DefaultTableModel) process_table.getModel();
        boolean added = false;
        //to check if 1 type is adding again
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if (tableModel.getValueAt(i, 0).toString().equals(process) && tableModel.getValueAt(i, 1).equals(garment_id)) {
                JOptionPane.showMessageDialog(this, "Already Added! Edit in table.");
                added = true;
                break;
            }
        }
        if (!added) {
            Object[] rawdata = {process, garment_id, garment_name, no_of_garments};
            tableModel.addRow(rawdata);
        }

        no_of_garments_spinner.setValue(0);
        garment_inpro_combo.setSelectedItem(null);
        add_to_table_button.setEnabled(false);
    }//GEN-LAST:event_add_to_table_buttonActionPerformed

    private void no_of_garments_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_no_of_garments_spinnerStateChanged
        GUIitemsValidator.limitminimumSpinnerValue(no_of_garments_spinner, 0);
        if (garment_inpro_combo.getSelectedItem() != null && no_of_garments_spinner.getValue().toString() != "0") {
            add_to_table_button.setEnabled(true);
        }
    }//GEN-LAST:event_no_of_garments_spinnerStateChanged

    private void garment_inpro_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_garment_inpro_comboItemStateChanged
        if (garment_inpro_combo.getSelectedItem() != null && no_of_garments_spinner.getValue().toString() != "0") {
            add_to_table_button.setEnabled(true);
        }
    }//GEN-LAST:event_garment_inpro_comboItemStateChanged

    private void cutting_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cutting_spinnerStateChanged
        GUIitemsValidator.limitminimumSpinnerValue(cutting_spinner, 0);
    }//GEN-LAST:event_cutting_spinnerStateChanged

    private void sewing_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sewing_spinnerStateChanged
        GUIitemsValidator.limitminimumSpinnerValue(sewing_spinner, 0);
    }//GEN-LAST:event_sewing_spinnerStateChanged

    private void dyeing_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dyeing_spinnerStateChanged
        GUIitemsValidator.limitminimumSpinnerValue(dyeing_spinner, 0);
    }//GEN-LAST:event_dyeing_spinnerStateChanged

    private void washing_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_washing_spinnerStateChanged
        GUIitemsValidator.limitminimumSpinnerValue(washing_spinner, 0);
    }//GEN-LAST:event_washing_spinnerStateChanged

    private void sewing_finish_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sewing_finish_spinnerStateChanged
        GUIitemsValidator.limitminimumSpinnerValue(sewing_finish_spinner, 0);
    }//GEN-LAST:event_sewing_finish_spinnerStateChanged

    private void completing_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_completing_spinnerStateChanged
        GUIitemsValidator.limitminimumSpinnerValue(completing_spinner, 0);
    }//GEN-LAST:event_completing_spinnerStateChanged

    void focustabbedpane(int num) {

        tab_pane_out.setSelectedIndex(num);

    }

    void requestFoucsForm() {
        garment_combo.requestFocus();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_to_table_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton cancel_button2;
    private javax.swing.JSpinner completing_spinner;
    private javax.swing.JSpinner cutting_spinner;
    private javax.swing.JTextField date_text;
    private javax.swing.JSpinner dyeing_spinner;
    private javax.swing.JComboBox<String> garment_combo;
    private javax.swing.JComboBox<String> garment_inpro_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner no_of_garments_spinner;
    private javax.swing.JTable process_table;
    private javax.swing.JComboBox<String> processes_combo;
    private javax.swing.JButton save_by_garment_button;
    private javax.swing.JButton save_by_process_button;
    private javax.swing.JSpinner sewing_finish_spinner;
    private javax.swing.JSpinner sewing_spinner;
    private javax.swing.JTabbedPane tab_pane_out;
    private javax.swing.JTabbedPane tabpane_in;
    private javax.swing.JSpinner washing_spinner;
    // End of variables declaration//GEN-END:variables
}
