/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gfcl.views;

import gfc.controller.DailyMaterialUsageController;
import gfc.controller.MaterialController;
import gfc.controller.StockController;
import gfc.models.DailyMaterialUsage;
import gfc.models.Material;
import gfc.models.Stock;
import gfcl.common_classes.ComboItemsAdder;
import gfcl.common_classes.IdGenerator;
import gfcl.connector.Connector;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gimhani Uthpala
 */
public class StockDetailFrame extends javax.swing.JInternalFrame {

    private MaterialController materialController;
    private StockController stockController;
    private DailyMaterialUsageController dailyMaterialUsageController;
    private ComboItemsAdder cia;

    /**
     * Creates new form StockDetailFrame
     */
    public StockDetailFrame() {
        try {
            initComponents();
            Connector sConnector = Connector.getSConnector();
            materialController = sConnector.getMaterialController();
            stockController = sConnector.getStockController();
            dailyMaterialUsageController = sConnector.getDailyMaterialUsageController();
            cia = new ComboItemsAdder();

            mat_id_text.setText(IdGenerator.generateNextMaterialID(materialController.getLastMaterialId()));
            stock_id_text.setText(IdGenerator.generateNextStockID(stockController.getLastStockId()));

            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date();
            stock_date_text.setText(dateFormat.format(date));
            daily_date_text.setText(dateFormat.format(date));
            new_date_text.setText(dateFormat.format(date));

            add_stock_button.setEnabled(false);

            this.materialtypecombo.setEditable(true);
            cia.addSimilarMaterialnames(materialtypecombo);

            this.daily_materialtypecombo.setEditable(true);
            cia.addSimilarOtherMaterialnames(daily_materialtypecombo);

            addDataToStockTable(dye_stock_table, "Dye");
            addDataToStockTable(cloth_stock_table, "Cloth");
            addDataToStockTable(thread_stock_table, "Thread");
            addDataToStockTable(wax_stock_table, "Wax");
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StockDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void addDataToStockTable(JTable table, String type) throws RemoteException, SQLException, ClassNotFoundException {
        DefaultTableModel stock_dtm = (DefaultTableModel) table.getModel();
        ArrayList<Material> list = new ArrayList<>();
        list = materialController.getAllMaterialsOfType(type);
        for (Material m : list) {
            Object[] rawdata = {m.getMat_id(), m.getMat_name(), m.getIn_stock()};
            stock_dtm.addRow(rawdata);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        tabpane = new javax.swing.JTabbedPane();
        add_stock_entry_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        mat_type_label = new javax.swing.JLabel();
        materialtypecombo = new javax.swing.JComboBox<>();
        amount_label = new javax.swing.JLabel();
        unit_price_label = new javax.swing.JLabel();
        unitprice_text = new javax.swing.JTextField();
        add_stock_button = new javax.swing.JButton();
        amount_text = new javax.swing.JTextField();
        amount_unit_label_2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        previous_stock_label = new javax.swing.JLabel();
        current_stock_label = new javax.swing.JLabel();
        current_stock_text = new javax.swing.JTextField();
        previous_stock_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mat_type_text = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stock_date_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stock_id_text = new javax.swing.JTextField();
        add_daily_usage_panel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        daily_prev_stock_label = new javax.swing.JLabel();
        daily_curr_stock_label = new javax.swing.JLabel();
        daily_current_stock_text = new javax.swing.JTextField();
        daily_pre_stock_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        daily_material_type_text = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        daily_mat_type_label = new javax.swing.JLabel();
        daily_materialtypecombo = new javax.swing.JComboBox<>();
        daily_amount_label = new javax.swing.JLabel();
        daily_addbutton = new javax.swing.JButton();
        daily_amount_text = new javax.swing.JTextField();
        date_label = new javax.swing.JLabel();
        daily_date_text = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        amount_unit_label_1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        add_new_panel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        intial_stock_panel = new javax.swing.JPanel();
        initial_stock_amount_label = new javax.swing.JLabel();
        initial_stock_amount_text = new javax.swing.JTextField();
        intialstock_unit_price_label = new javax.swing.JLabel();
        initial_stock_unitprice_text = new javax.swing.JTextField();
        amount_unit_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        new_date_text = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        material_id_label = new javax.swing.JLabel();
        mat_id_text = new javax.swing.JTextField();
        mat_name_label = new javax.swing.JLabel();
        mat_name_text = new javax.swing.JTextField();
        material_type_label = new javax.swing.JLabel();
        mat_type_combo = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        addnew_mat_button = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        view_current_stocks_panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        clothstock_panel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        cloth_stock_table = new javax.swing.JTable();
        dye_panel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        dye_stock_table = new javax.swing.JTable();
        thread_panel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        thread_stock_table = new javax.swing.JTable();
        wax_panel = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        wax_stock_table = new javax.swing.JTable();

        tabpane.setForeground(new java.awt.Color(0, 0, 204));
        tabpane.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mat_type_label.setText("Material type:");

        materialtypecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                materialtypecomboItemStateChanged(evt);
            }
        });
        materialtypecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialtypecomboActionPerformed(evt);
            }
        });

        amount_label.setText("Amount: ");

        unit_price_label.setText("Unit price:");

        unitprice_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitprice_textKeyReleased(evt);
            }
        });

        add_stock_button.setText("Add to stock");
        add_stock_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_stock_buttonActionPerformed(evt);
            }
        });

        amount_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amount_textKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mat_type_label)
                        .addGap(23, 23, 23)
                        .addComponent(materialtypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount_label)
                            .addComponent(unit_price_label))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(unitprice_text)
                            .addComponent(amount_text, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amount_unit_label_2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(add_stock_button, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(mat_type_label))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(materialtypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_label)
                    .addComponent(amount_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount_unit_label_2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unit_price_label)
                    .addComponent(unitprice_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(add_stock_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Last added"));

        previous_stock_label.setText("Previous Stock:");

        current_stock_label.setText("Current Stock:");

        current_stock_text.setEditable(false);

        previous_stock_text.setEditable(false);

        jLabel2.setText("Material type:");

        mat_type_text.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(current_stock_label)
                        .addGap(18, 18, 18)
                        .addComponent(current_stock_text, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(previous_stock_label)
                        .addGap(18, 18, 18)
                        .addComponent(previous_stock_text, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mat_type_text, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mat_type_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previous_stock_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previous_stock_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(current_stock_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(current_stock_label))
                .addGap(25, 25, 25))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Date:");

        jLabel3.setText("Stock ID:");

        stock_id_text.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(stock_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(stock_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stock_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(stock_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout add_stock_entry_panelLayout = new javax.swing.GroupLayout(add_stock_entry_panel);
        add_stock_entry_panel.setLayout(add_stock_entry_panelLayout);
        add_stock_entry_panelLayout.setHorizontalGroup(
            add_stock_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_stock_entry_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        add_stock_entry_panelLayout.setVerticalGroup(
            add_stock_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_stock_entry_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabpane.addTab("Add stock entry", new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/baggage_cart_box.png")), add_stock_entry_panel); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Last updated"));

        daily_prev_stock_label.setText("Previous Stock:");

        daily_curr_stock_label.setText("Current Stock:");

        daily_current_stock_text.setEditable(false);

        daily_pre_stock_text.setEditable(false);

        jLabel4.setText("Material :");

        daily_material_type_text.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daily_prev_stock_label)
                    .addComponent(jLabel4)
                    .addComponent(daily_curr_stock_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daily_current_stock_text, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daily_pre_stock_text, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daily_material_type_text, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(daily_material_type_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daily_prev_stock_label)
                    .addComponent(daily_pre_stock_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daily_curr_stock_label)
                    .addComponent(daily_current_stock_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        daily_mat_type_label.setText("Material type:");

        daily_materialtypecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                daily_materialtypecomboItemStateChanged(evt);
            }
        });

        daily_amount_label.setText("Amount: ");

        daily_addbutton.setText("Add");
        daily_addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daily_addbuttonActionPerformed(evt);
            }
        });

        daily_amount_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                daily_amount_textKeyReleased(evt);
            }
        });

        date_label.setText("Date:");

        jButton1.setText("Add Cloth Usages");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("This is to add daily usages of Dyes, Threads and Waxes. Use above button to add cloth usages.");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(daily_addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(date_label)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(daily_mat_type_label)
                                            .addComponent(daily_amount_label))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(daily_amount_text, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(amount_unit_label_1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(daily_materialtypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(daily_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(14, 14, 14))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daily_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_label)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daily_mat_type_label)
                    .addComponent(daily_materialtypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daily_amount_label)
                    .addComponent(daily_amount_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount_unit_label_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(daily_addbutton)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout add_daily_usage_panelLayout = new javax.swing.GroupLayout(add_daily_usage_panel);
        add_daily_usage_panel.setLayout(add_daily_usage_panelLayout);
        add_daily_usage_panelLayout.setHorizontalGroup(
            add_daily_usage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_daily_usage_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_daily_usage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        add_daily_usage_panelLayout.setVerticalGroup(
            add_daily_usage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_daily_usage_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(671, Short.MAX_VALUE))
        );

        tabpane.addTab("Add daily usage", new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/box_down.png")), add_daily_usage_panel); // NOI18N

        intial_stock_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Initial Stcok"));

        initial_stock_amount_label.setText("Amount: ");

        intialstock_unit_price_label.setText("Unit price:");

        javax.swing.GroupLayout intial_stock_panelLayout = new javax.swing.GroupLayout(intial_stock_panel);
        intial_stock_panel.setLayout(intial_stock_panelLayout);
        intial_stock_panelLayout.setHorizontalGroup(
            intial_stock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intial_stock_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intial_stock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intialstock_unit_price_label)
                    .addComponent(initial_stock_amount_label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(intial_stock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(initial_stock_amount_text, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(initial_stock_unitprice_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amount_unit_label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        intial_stock_panelLayout.setVerticalGroup(
            intial_stock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intial_stock_panelLayout.createSequentialGroup()
                .addGroup(intial_stock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(intial_stock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(initial_stock_amount_text, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(initial_stock_amount_label))
                    .addGroup(intial_stock_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(amount_unit_label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(intial_stock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intialstock_unit_price_label)
                    .addComponent(initial_stock_unitprice_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jLabel5.setText("Date:");

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        material_id_label.setText("Material ID:");

        mat_id_text.setEditable(false);

        mat_name_label.setText("Material Name:");

        material_type_label.setText("Material type:");

        mat_type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cloth", "Dye", "Wax", "Thread" }));
        mat_type_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mat_type_comboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mat_name_label)
                            .addComponent(material_id_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mat_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mat_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(material_type_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mat_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(material_id_label)
                    .addComponent(mat_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mat_name_label)
                    .addComponent(mat_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(material_type_label)
                    .addComponent(mat_type_combo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addnew_mat_button.setText("Save");
        addnew_mat_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnew_mat_buttonActionPerformed(evt);
            }
        });

        cancelbutton.setText("Cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addnew_mat_button, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addnew_mat_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(new_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intial_stock_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(524, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(new_date_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intial_stock_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel10);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout add_new_panelLayout = new javax.swing.GroupLayout(add_new_panel);
        add_new_panel.setLayout(add_new_panelLayout);
        add_new_panelLayout.setHorizontalGroup(
            add_new_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_new_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 571, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );
        add_new_panelLayout.setVerticalGroup(
            add_new_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_new_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(582, Short.MAX_VALUE))
        );

        tabpane.addTab("Add new material type", new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/box--plus.png")), add_new_panel); // NOI18N

        clothstock_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cloth Stocks"));

        cloth_stock_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mat_ID", "Name", "Stock(m)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cloth_stock_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(cloth_stock_table);

        javax.swing.GroupLayout clothstock_panelLayout = new javax.swing.GroupLayout(clothstock_panel);
        clothstock_panel.setLayout(clothstock_panelLayout);
        clothstock_panelLayout.setHorizontalGroup(
            clothstock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clothstock_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clothstock_panelLayout.setVerticalGroup(
            clothstock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clothstock_panelLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        dye_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dye stocks"));

        dye_stock_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mat_ID", "Name", "Stock(kg)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dye_stock_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(dye_stock_table);

        javax.swing.GroupLayout dye_panelLayout = new javax.swing.GroupLayout(dye_panel);
        dye_panel.setLayout(dye_panelLayout);
        dye_panelLayout.setHorizontalGroup(
            dye_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dye_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dye_panelLayout.setVerticalGroup(
            dye_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dye_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        thread_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Thread Stocks"));

        thread_stock_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mat_ID", "Name", "Stock(thread rolls)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        thread_stock_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(thread_stock_table);

        javax.swing.GroupLayout thread_panelLayout = new javax.swing.GroupLayout(thread_panel);
        thread_panel.setLayout(thread_panelLayout);
        thread_panelLayout.setHorizontalGroup(
            thread_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thread_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        thread_panelLayout.setVerticalGroup(
            thread_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thread_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        wax_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Wax stocks"));

        wax_stock_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mat_ID", "Name", "Stock(kg)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(wax_stock_table);

        javax.swing.GroupLayout wax_panelLayout = new javax.swing.GroupLayout(wax_panel);
        wax_panel.setLayout(wax_panelLayout);
        wax_panelLayout.setHorizontalGroup(
            wax_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wax_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        wax_panelLayout.setVerticalGroup(
            wax_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wax_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wax_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dye_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thread_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clothstock_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clothstock_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dye_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thread_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wax_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(868, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel14);

        jScrollPane4.setViewportView(jScrollPane5);

        javax.swing.GroupLayout view_current_stocks_panelLayout = new javax.swing.GroupLayout(view_current_stocks_panel);
        view_current_stocks_panel.setLayout(view_current_stocks_panelLayout);
        view_current_stocks_panelLayout.setHorizontalGroup(
            view_current_stocks_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        view_current_stocks_panelLayout.setVerticalGroup(
            view_current_stocks_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_current_stocks_panelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 145, Short.MAX_VALUE))
        );

        tabpane.addTab("View current stocks", new javax.swing.ImageIcon(getClass().getResource("/gfcl/images/box_search.png")), view_current_stocks_panel); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabpane))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addnew_mat_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnew_mat_buttonActionPerformed
        try {
            String mat_id = mat_id_text.getText();
            String mat_name = mat_name_text.getText();
            String mat_type = mat_type_combo.getSelectedItem().toString();
            String date = new_date_text.getText();
            double new_stock = Double.valueOf(initial_stock_amount_text.getText());
            double unit_price = Double.valueOf(initial_stock_unitprice_text.getText());
            Material material = new Material(mat_id, mat_name, mat_type, new_stock);
            int addNewMaterial = materialController.addNewMaterial(material);
            if (addNewMaterial > 0) {
                if (!"".equals(initial_stock_amount_text.getText()) && !"".equals(initial_stock_unitprice_text.getText())) {
                    Stock stock = new Stock(IdGenerator.generateNextStockID(stockController.getLastStockId()), mat_id, date, new_stock, unit_price);
                    boolean updateStock = stockController.updateStock(stock);
                    if (updateStock) {
                        JOptionPane.showMessageDialog(this, "New Material type was added!");
                    } else {
                        JOptionPane.showMessageDialog(this, "New Material type was not added!");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "New Material type was not added!");
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StockDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addnew_mat_buttonActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void amount_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amount_textKeyReleased
        if (amount_text.getText().trim().length() != 0 && unitprice_text.getText().trim().length() != 0) {
            add_stock_button.setEnabled(true);
        } else {
            add_stock_button.setEnabled(false);
        }
    }//GEN-LAST:event_amount_textKeyReleased

    private void unitprice_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitprice_textKeyReleased
        if (amount_text.getText().trim().length() != 0 && unitprice_text.getText().trim().length() != 0) {
            add_stock_button.setEnabled(true);
        } else {
            add_stock_button.setEnabled(false);
        }
    }//GEN-LAST:event_unitprice_textKeyReleased

    private void materialtypecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_materialtypecomboItemStateChanged
        try {
            if (materialtypecombo.getSelectedItem() != null) {
                String selected = materialtypecombo.getSelectedItem().toString();
                String[] sel = selected.split("-");
                String mat_id = sel[2];
                switch (sel[1]) {
                    case "Cloth":
                        amount_unit_label_2.setText("meters");
                        break;
                    case "Dye":
                        amount_unit_label_2.setText("kg");
                        break;
                    case "Wax":
                        amount_unit_label_2.setText("litres");
                        break;
                    case "Thread":
                        amount_unit_label_2.setText("meters");
                        break;

                }
                Material mat = materialController.searchMaterial(mat_id);
                previous_stock_text.setText(String.valueOf(mat.getIn_stock()));
                mat_type_text.setText(selected);
                current_stock_text.setText("");
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StockDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_materialtypecomboItemStateChanged

    private void add_stock_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_stock_buttonActionPerformed
        try {
            double amount = Double.valueOf(amount_text.getText());
            double unit_price = Double.valueOf(unitprice_text.getText());
            String selected[] = materialtypecombo.getSelectedItem().toString().split("-");
            String mat_id = selected[2];
            String date = stock_date_text.getText();
            String stock_id = stock_id_text.getText();
            Stock stock = new Stock(stock_id, mat_id, date, amount, unit_price);
            boolean updateStock = stockController.updateStock(stock);
            current_stock_text.setText(String.valueOf(materialController.searchMaterial(mat_id).getIn_stock()));
            if (updateStock) {
                JOptionPane.showMessageDialog(this, "Stock updated");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update stock");

            }
            stock_id_text.setText(IdGenerator.generateNextStockID(stockController.getLastStockId()));
            add_stock_button.setEnabled(false);
            materialtypecombo.setSelectedItem(null);
            amount_text.setText("");
            unitprice_text.setText("");
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StockDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_add_stock_buttonActionPerformed

    private void materialtypecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialtypecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialtypecomboActionPerformed

    private void daily_addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daily_addbuttonActionPerformed
        try {
            double amount = Double.valueOf(daily_amount_text.getText());
            String text = daily_materialtypecombo.getSelectedItem().toString();
            String selected[] = text.split("-");
            String mat_id = selected[2];
            String date = daily_date_text.getText();
            DailyMaterialUsage dmu = new DailyMaterialUsage(mat_id, date, amount);
            Material searchMaterial = materialController.searchMaterial(mat_id);
            Double new_stock = searchMaterial.getIn_stock() - dmu.getAmount();
            if (new_stock >= 0 && !dailyMaterialUsageController.isDateAdded(mat_id, date)) {
                boolean addDailyUsage = dailyMaterialUsageController.addDailyUsage(dmu);
                if (addDailyUsage) {
                    JOptionPane.showMessageDialog(this, "Daily usage added!");
                } else {
                    JOptionPane.showMessageDialog(this, "Daily usage updating failed!");
                }
            } else if (new_stock < 0) {
                JOptionPane.showMessageDialog(this, "Used amount exceeded stored amount.");
            } else {
                JOptionPane.showMessageDialog(this, "Already added");
            }
            daily_current_stock_text.setText(String.valueOf(materialController.searchMaterial(mat_id).getIn_stock()));
            daily_addbutton.setEnabled(false);
            daily_materialtypecombo.setSelectedItem(null);
            daily_amount_text.setText("");
            daily_material_type_text.setText(text);

        } catch (RemoteException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StockDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_daily_addbuttonActionPerformed

    private void daily_materialtypecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_daily_materialtypecomboItemStateChanged
        try {
            if (daily_materialtypecombo.getSelectedItem() != null) {
                String selected = daily_materialtypecombo.getSelectedItem().toString();
                String[] sel = selected.split("-");
                String mat_id = sel[2];
                switch (sel[1]) {
                    case "Cloth":
                        amount_unit_label_1.setText("meters");
                        break;
                    case "Dye":
                        amount_unit_label_1.setText("kg");
                        break;
                    case "Wax":
                        amount_unit_label_1.setText("litres");
                        break;
                    case "Thread":
                        amount_unit_label_1.setText("meters");
                        break;

                }
                Material mat = materialController.searchMaterial(mat_id);
                daily_pre_stock_text.setText(String.valueOf(mat.getIn_stock()));
                daily_material_type_text.setText(selected);
                daily_current_stock_text.setText("");
                if (daily_amount_text.getText().trim().length() != 0) {
                    daily_addbutton.setEnabled(true);
                } else {
                    daily_addbutton.setEnabled(false);
                }
            } else {
                daily_addbutton.setEnabled(false);
            }
        } catch (RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StockDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_daily_materialtypecomboItemStateChanged

    private void daily_amount_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_daily_amount_textKeyReleased
        if (daily_materialtypecombo.getSelectedItem() != null && daily_amount_text.getText().trim().length() != 0) {
            daily_addbutton.setEnabled(true);
        } else {
            daily_addbutton.setEnabled(false);
        }
    }//GEN-LAST:event_daily_amount_textKeyReleased

    private void mat_type_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mat_type_comboItemStateChanged
        switch (mat_type_combo.getSelectedItem().toString()) {
            case "Cloth":
                amount_unit_label.setText("meters");
                break;
            case "Dye":
                amount_unit_label.setText("kg");
                break;
            case "Wax":
                amount_unit_label.setText("litres");
                break;
            case "Thread":
                amount_unit_label.setText("meters");
                break;

        }
    }//GEN-LAST:event_mat_type_comboItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrontPage frontPage = FrontPage.getInstance();
        ProductionDetailFrame pdf = new ProductionDetailFrame();
        frontPage.setDesktopPaneForProduction(pdf, 1);
    }//GEN-LAST:event_jButton1ActionPerformed

    void focustabbedpane(int num) {
        tabpane.setSelectedIndex(num);
    }

    void requestFoucsForm() {
        materialtypecombo.requestFocus();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_daily_usage_panel;
    private javax.swing.JPanel add_new_panel;
    private javax.swing.JButton add_stock_button;
    private javax.swing.JPanel add_stock_entry_panel;
    private javax.swing.JButton addnew_mat_button;
    private javax.swing.JLabel amount_label;
    private javax.swing.JTextField amount_text;
    private javax.swing.JLabel amount_unit_label;
    private javax.swing.JLabel amount_unit_label_1;
    private javax.swing.JLabel amount_unit_label_2;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JTable cloth_stock_table;
    private javax.swing.JPanel clothstock_panel;
    private javax.swing.JLabel current_stock_label;
    private javax.swing.JTextField current_stock_text;
    private javax.swing.JButton daily_addbutton;
    private javax.swing.JLabel daily_amount_label;
    private javax.swing.JTextField daily_amount_text;
    private javax.swing.JLabel daily_curr_stock_label;
    private javax.swing.JTextField daily_current_stock_text;
    private javax.swing.JTextField daily_date_text;
    private javax.swing.JLabel daily_mat_type_label;
    private javax.swing.JTextField daily_material_type_text;
    private javax.swing.JComboBox<String> daily_materialtypecombo;
    private javax.swing.JTextField daily_pre_stock_text;
    private javax.swing.JLabel daily_prev_stock_label;
    private javax.swing.JLabel date_label;
    private javax.swing.JPanel dye_panel;
    private javax.swing.JTable dye_stock_table;
    private javax.swing.JLabel initial_stock_amount_label;
    private javax.swing.JTextField initial_stock_amount_text;
    private javax.swing.JTextField initial_stock_unitprice_text;
    private javax.swing.JPanel intial_stock_panel;
    private javax.swing.JLabel intialstock_unit_price_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mat_id_text;
    private javax.swing.JLabel mat_name_label;
    private javax.swing.JTextField mat_name_text;
    private javax.swing.JComboBox<String> mat_type_combo;
    private javax.swing.JLabel mat_type_label;
    private javax.swing.JTextField mat_type_text;
    private javax.swing.JLabel material_id_label;
    private javax.swing.JLabel material_type_label;
    private javax.swing.JComboBox<String> materialtypecombo;
    private javax.swing.JTextField new_date_text;
    private javax.swing.JLabel previous_stock_label;
    private javax.swing.JTextField previous_stock_text;
    private javax.swing.JTextField stock_date_text;
    private javax.swing.JTextField stock_id_text;
    private javax.swing.JTabbedPane tabpane;
    private javax.swing.JPanel thread_panel;
    private javax.swing.JTable thread_stock_table;
    private javax.swing.JLabel unit_price_label;
    private javax.swing.JTextField unitprice_text;
    private javax.swing.JPanel view_current_stocks_panel;
    private javax.swing.JPanel wax_panel;
    private javax.swing.JTable wax_stock_table;
    // End of variables declaration//GEN-END:variables

    public void setDisabledTabs(boolean tab1,boolean tab2,boolean tab3,boolean tab4){
        tabpane.setEnabledAt(0,tab1 );
        tabpane.setEnabledAt(1,tab2 );
        tabpane.setEnabledAt(2,tab3 );
        tabpane.setEnabledAt(3,tab4 );
    }

   
}
